<?php

namespace App\Controllers;

use App\Models\ProdutoModel;

use CodeIgniter\Controller;

class InsertProdutos extends Controller
{
    private $produto_model;

    function __construct()
    {
        $this->produto_model = new ProdutoModel();
    }

    public function index()
    {
        $produtos = array(
            array('nome' => 'SORVETE CREME MEL CHOCOLATE 10KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '1', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL CHOCOLATE 10KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '20089900', 'id_unidade' => '1', 'id_empresa' => '11'),
            array('nome' => 'PANQUECA CARNE', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '9.5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'PANQUECA  FRANGO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '9.5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'PANQUECA STROGONOFF DE FRANGO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'PANQUECA BOLONHESA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10.5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'PANQUECA A MODA CABANA FRANGO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10.5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'PANQUECA CARNE DE SOL TRADICIONAL ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10.5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'PANQUECA A MODA DA CASA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10.5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'PANQUECA PRESUNTO E QUEIJO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAPIOCA 1 MANTEIGA E MUSSARELA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAPIOCA  2 MUSSARELA E PRESUNTO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAPIOCA 4 FRANGO, MUSSARELA, TOMATE, CEBOLA E CATUPIRY', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAPIOCA 3 FRANGO, MUSSARELA E CATUPIRY', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAPIOCA 5 CARNE DE SOL, MUSSARELA E CATUPIRY', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAPIOCA 7 CARNE DE SOL, MUSSARELA, TOMATE, CEBOLA..', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAPIOCA 8 CARNE DE SOL, MUSSARELA, QUEIJO CREMOSO...', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SUCO ACEROLA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20029010', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SUCO MORANGO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20029010', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SUCO CAJA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20029010', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SUCO AÇAÍ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20029010', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SUCO CUPUAÇU', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20029010', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SUCO MARACUJÁ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20029010', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SUCO MANGA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20029010', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SUCO LARANJA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '6', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20029010', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAI PURO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'ACAI PURO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '15', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ PURO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '19', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '20', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADAS P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADAS M ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '18', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADAS G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE NINHO EM CAMADAS P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE NINHO EM CAMADAS M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '18', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE NINHO EM CAMADAS G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE NINHO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE NINHO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ LEITE NINHO G ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '20', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ MORANGO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ MORANGO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ BANANA P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ BANANA M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ BANANA G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '20', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ CHOCOLATE P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ CHOCOLATE M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ C/ CHOCOLATE G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '21', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ MIX TROPICAL P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ MIX TROPICAL M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ MIX TROPICAL G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '20', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ MIX TROPICAL C/ SORVETE P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ MIX TROPICAL C/ SORVETE M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '18', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ MIX TROPICAL C/ SORVETE G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO MIX TROPICAL C/ SORVETE P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO MIX TROPICAL C/ SORVETE', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '20', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO MIX TROPICAL C/ SORVETE', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '24', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO MIX TROPICAL P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO MIX TROPICAL C/ SORVETE M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '18', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO MIX TROPICAL  G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '23', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CASADINHO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '20', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CUPUAÇU PURO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CUPUAÇU PURO M ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '15', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CUPUAÇU PURO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '19', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ BATIDO C/ FRUTAS P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ BATIDO C/ FRUTAS M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'ACIONAL', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '2', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CREME DE AÇAÍ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'ENERGÉTICO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'ENERGÉTICO CABANA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'SUCO FRUTAS', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '5', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20098000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'SUCO DE LARANJA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '6', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20098000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'CREME DE FRUTAS', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '8', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '20098000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'ÁGUA MINERAL', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '3', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '22011000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'ÁGUA MINERAL C/ GÁS', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '3', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '22011000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'REFRIGERANTE LATA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '4', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '22021000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'TORTINHA DE FRANGO C/ MOLHO BRANCO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'PANQUECAS', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'TAPIOCA DE FRANGO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'TAPIOCA PRESUNTO E QUEIJO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'TAPIOCA CARNE DE SOL', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'TAPIOCA CARNE DE SOL A MODA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'TAPIOCA DE FRANGO A MODA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ CABANA 400ML', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'BARCA DE AÇAÍ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '35', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ PURO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '11', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ PURO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '15', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ PURO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '21', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ PURO GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '28', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '30', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADA P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADA M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADA G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '23', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADA GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '30', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE NINHO EM CAMADA P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADA M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADA G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '23', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO EM CAMADA GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '30', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ LEITE CONDENSADO GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '30', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ MORANGO P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ MORANGO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ MORANGO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ MORANGO GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '30', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ BANANA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ BANANA P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ BANANA G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ BANANA GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '30', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ CHOCOLATE P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ CHOCOLATE M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ CHOCOLATE G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '23', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ C/ CHOCOLATE GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '29', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MIX TROPICAL P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MIX TROPICAL M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MIX TROPICAL G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MIX TROPICAL GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '28', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MIX TROPICAL C/ SORVETE P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MIX TROPICAL C/ SORVETE M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '18', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MIX TROPICAL C/ SORVETE G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '23', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MIX TROPICAL C/ SORVETE GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '29', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CASADINHO MIX TROPICAL C/ SORVETE', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CASADINHO MIX TROPICAL C/ SORVETE M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CASADINHO MIX TROPICAL C/ SORVETE G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CASADINHO MIX TROPICAL C/ SORVETE GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '28', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CASADINHO ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CASADINHO M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CASADINHO G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CASADINHO GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '28', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ BATIDO C/ FRUTA P', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '13', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ BATIDO C/ FRUTA M', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ BATIDO C/ FRUTA G', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '22', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ BATIDO C/ FRUTA GG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '28', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAÇA NUTELLA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAÇA MIX', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '15', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAÇA MORANGO C/ NUTELLA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '17', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAÇA CABANA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TAÇA MORANGO GOURMET', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '16', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CREME AÇAÍ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'ENERGÉTICO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '12', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'ENERGÉTICO CABANA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '14', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'CREME DE FRUTA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '8', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'REFRIGERANTE LATA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '4', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '22021000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'BARCA DE AÇAÍ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '37', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'ÁGUA MINERAL', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '3', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '22011000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TORTINHA FRANGO C/ MOLHO BRANCO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TORTINHA DE FRANGO C/ CREME DE MILHO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'TORTINHA DE CARNE DE SOL', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MACUNAIMA 1 KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ SÃO PEDRO 1 kg', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ MACUNAIMA KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'AÇAÍ SÃO PEDRO 1 KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '08119000', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'TORTINHA DE FRANGO C/ CREME DE MILHO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'TORTINHA DE CARNE DE SOL', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L CEREJA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '110', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L COCO BRANCO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L CREME', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L FLOCOSS', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L MORANGO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '3', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L CHOCONINHO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L BOLO DE NOIVA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '110', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L CHOCOMENTA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L COCO BRANCO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L CREME', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L FLOCOS', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L CHOCOLATE BRANCO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L MORANGO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L BOLO DE ANIVERSARIO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '110', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L BANANA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L LEITE CONDENSADO ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L CHOCONINHO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L ABACAXI AO VINHO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'AÇAÍ NO KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '32.99', 'CFOP_NFe' => '5101', 'CFOP_NFCe' => '5101', 'NCM' => '08119000', 'id_unidade' => '4', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L CUPUAÇU 10L', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL ABACAXI AO VINHO 10KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL BANANA 10KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L CHOCOLATE BRANCO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL MARACUJA 10KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L CUPUAÇU ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '3', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L NAPOLITANO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10KG PAVE', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '69.56', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L CEREJA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '110', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L PAVE', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREME MEL 10L NAPOLITANO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL 10L SUBLIMEL BLACK', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MELMARACUJA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '20089900', 'id_unidade' => '1', 'id_empresa' => '11'),
            array('nome' => 'CREME MEL SUBLIME ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '20089900', 'id_unidade' => '1', 'id_empresa' => '11'),
            array('nome' => 'CREME MEL ABACAXI', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '120', 'CFOP_NFe' => '5403', 'CFOP_NFCe' => '5102', 'NCM' => '20089900', 'id_unidade' => '1', 'id_empresa' => '11'),
            array('nome' => 'FRUTAS VERMELHAS', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'FRUTAS VERMELHAS', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '91', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '21050090', 'id_unidade' => '2', 'id_empresa' => '10'),
            array('nome' => 'SORVETE CREME MEL CHICLETE', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '1', 'id_empresa' => '11'),
            array('nome' => 'SORVETE CREWME MEL CREAM COOKIES ', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '1', 'id_empresa' => '11'),
            array('nome' => 'FANATSIA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '1', 'id_empresa' => '10'),
            array('nome' => 'CREME MEL FANTASIA', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '7', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '19059090', 'id_unidade' => '1', 'id_empresa' => '11'),
            array('nome' => 'AÇAI BELLO FRUTO', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '1', 'CFOP_NFe' => '111', 'CFOP_NFCe' => '111', 'NCM' => '111', 'id_unidade' => '4', 'id_empresa' => '11'),
            array('nome' => 'AÇAI BELLO FRUTO KG', 'codigo_de_barras' => 'SEM GTIN', 'valor_unitario' => '10', 'CFOP_NFe' => '5102', 'CFOP_NFCe' => '5102', 'NCM' => '08119000', 'id_unidade' => '4', 'id_empresa' => '11')
        );

        foreach($produtos as $produto):
            $produto['id_contador'] = 1;
            $produto['CFOP_Externo'] = 6102;

            $this->produto_model
                            ->insert($produto);
        endforeach;
    }
}
